name: Tester yaml

on:
  workflow_call:
env:
  JEST_JUNIT_OUTPUT_DIR: ./reports/junit/
jobs:
  yarn_tester_web:
    runs-on: ubuntu-latest
#    strategy:
#      matrix:
#        shard: [1/3, 2/3, 3/3]
    steps:
      - uses: actions/checkout@v3
      - uses: SimenB/github-actions-cpu-cores@v1
        id: cpu-cores
      - uses: actions/cache@v3
        with:
          path: |
            node_modules
            ~/.cache/yarn
          key: v1-yarn-dependency-cache-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            v1-yarn-dependency-cache-${{ hashFiles('**/yarn.lock') }}
      - uses: actions/cache@v3
        id: yarn-test-web-cache
        with:
          path: .jest/cache
          key: v1-yarn-test-web-cache-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            v1-yarn-test-web-cache-${{ hashFiles('**/yarn.lock') }}
      - run: yarn test:unit:web:ci --shard=${{ matrix.shard }} --max-workers ${{ steps.cpu-cores.outputs.count }}
        continue-on-error: true

#  yarn_test_native:
#    runs-on: ubuntu-latest
#    strategy:
#      matrix:
#        shard: [1/3, 2/3, 3/3]
#    steps:
#      - uses: actions/checkout@v3
#      - uses: actions/cache@v3
#        with:
#          path: |
#            node_modules
#            ~/.cache/yarn
#          key: v1-yarn-dependency-cache-${{ hashFiles('**/yarn.lock') }}
#          restore-keys: |
#            v1-yarn-dependency-cache-${{ hashFiles('**/yarn.lock') }}
#      - uses: actions/cache@v3
#        with:
#          path: .jest/cache
#          key: v1-yarn-test-native-cache-${{ hashFiles('**/yarn.lock') }}-${{ matrix.testGroup }}
#          restore-keys: |
#            v1-yarn-test-native-cache-${{ hashFiles('**/yarn.lock') }}-${{ matrix.testGroup }}
#      - run: yarn test:unit:ci --shard=${{ matrix.shard }}
#        continue-on-error: true
#
#  yarn_test_proxy:
#    runs-on: ubuntu-latest
#    strategy:
#      matrix:
#        shard: [1/3, 2/3, 3/3]
#    steps:
#      - uses: actions/checkout@v3
#      - uses: actions/cache@v3
#        id: yarn-test-native-cache
#        with:
#          path: |
#            node_modules
#            ~/.cache/yarn
#          key: v1-yarn-dependency-cache-${{ hashFiles('**/yarn.lock') }}
#          restore-keys: |
#            v1-yarn-dependency-cache-${{ hashFiles('**/yarn.lock') }}
#      - run:  yarn install --immutable --cwd server
#      - uses: actions/cache@v3
#        with:
#          path: .jest/cache
#          key: v1-yarn-test-native-cache-${{ hashFiles('**/yarn.lock') }}-${{ matrix.testGroup }}
#          restore-keys: |
#            v1-yarn-test-native-cache-${{ hashFiles('**/yarn.lock') }}-${{ matrix.testGroup }}
#      - run: yarn test:unit:ci --shard=${{ matrix.shard }}
#        continue-on-error: true
