name: Initiate workflow

on:
  push:

jobs:
  yarn-install:
    uses: ./.github/workflows/dev_on_workflow_install.yml
 # yarn-linter:
  #  needs: yarn-install
   # uses:  ./.github/workflows/dev_on_workflow_linter_ts.yml
 # yarn-tester:
  #  needs: yarn-linter
   # uses: ./.github/workflows/dev_on_workflow_tester.yml
    #secrets:
     # SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      #SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
  soft-deploy-testing:
    needs: yarn-install
    if: github.ref == 'refs/heads/dev_wip_anouk_hard_testing' && startsWith(github.event.ref, 'refs/tags/*') != true
    uses: ./.github/workflows/dev_on_workflow_environment_deploy.yml
    with:
      TYPE: "soft"
      ENV: "testing"
    secrets:
      SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
      ANDROID_APPCENTER_API_TOKEN: ${{ secrets.ANDROID_TESTING_APPCENTER_API_TOKEN }}
      IOS_APPCENTER_API_TOKEN: ${{ secrets.IOS_TESTING_APPCENTER_API_TOKEN }}
      SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
  hard-deploy-testing:
    needs: yarn-install
    if: github.ref == 'refs/heads/dev_wip_anouk_hard_testing' && startsWith(github.ref, 'refs/tags/jaimlechatdeBruno')
    uses: ./.github/workflows/dev_on_workflow_environment_deploy.yml
    with:
      TYPE: "hard"
      ENV: "testing"
    secrets:
      SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
      ANDROID_APPCENTER_API_TOKEN: ${{ secrets.ANDROID_TESTING_APPCENTER_API_TOKEN }}
      IOS_APPCENTER_API_TOKEN: ${{ secrets.IOS_TESTING_APPCENTER_API_TOKEN }}
      SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
