name: Validate dev branch

on:
  push:

jobs:
  yarn-install:
    uses: ./.github/workflows/dev_on_workflow_install.yml
  sentry-on-deploy:
    needs: yarn-install
    uses: ./.github/workflows/dev_on_workflow_sentry_on_deploy.yml
    with:
      ENV: "testing"
    secrets:
      SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
      ANDROID_APPCENTER_API_TOKEN: ${{ secrets.ANDROID_TESTING_APPCENTER_API_TOKEN }}
      IOS_APPCENTER_API_TOKEN: ${{ secrets.IOS_TESTING_APPCENTER_API_TOKEN }}
      SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
