name: Build and deploy storybook to Github Pages

on:
  push:

jobs:
  build-and-deploy-storybook:
    runs-on: [self-hosted, linux, X64]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install Yarn
        run: npm install -g yarn
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: yarn
      - name: Install dependencies
        run: yarn install
