name: Install runtime environment and dependencies

on:
  workflow_call:

jobs:
  yarn-install:
    runs-on: [self-hosted, linux, x64]
    container:
      image: node:16
    steps:
      - uses: actions/checkout@v3
      - name: Setup java
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
      - name: Setup Android SDK
        uses: android-actions/setup-android@v2
      - uses: actions/cache@v3
        id: yarn-modules-cache
        with:
          path: |
            node_modules
            ~/.cache/yarn
          key: v1-yarn-dependency-cache-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            v1-yarn-dependency-cache-${{ hashFiles('**/yarn.lock') }}
      - run: yarn install 
        if: steps.yarn-modules-cache.outputs.cache-hit != 'true'
  bundle-install:
    runs-on: [self-hosted, linux, x64]
    container:
    steps:
      - uses: actions/checkout@v3
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - name: Install Gem dependencies
        run: bundle install --path=vendor/bundle
