name: Initiate workflow

on:
  push:

permissions:
      contents: 'read'
      id-token: 'write'
jobs:
  yarn-install:
    uses: ./.github/workflows/dev_on_workflow_install.yml
  yarn-linter:
    needs: yarn-install
    uses: ./.github/workflows/dev_on_workflow_linter_ts.yml
  yarn-tester:
    needs: yarn-linter
    uses: ./.github/workflows/dev_on_workflow_tester.yml
    secrets:
      GCP_EHP_SERVICE_ACCOUNT: ${{ secrets.GCP_EHP_SERVICE_ACCOUNT }}
      GCP_EHP_WORKLOAD_IDENTITY_PROVIDER: ${{ secrets.GCP_EHP_WORKLOAD_IDENTITY_PROVIDER }}
      #  yarn-storybook:
      #    needs: yarn-linter
      #    uses: ./.github/workflows/dev_on_workflow_storybook.yml
      #  soft-deploy-testing:
      #    needs: yarn-install
      #    if: github.ref == 'refs/heads/master'
      #    uses: ./.github/workflows/dev_on_workflow_environment_deploy.yml
      #    with:
      #      TYPE: "soft"
      #      ENV: "testing"
      #      environment: testing
      #    secrets:
      #      SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
      #      ANDROID_APPCENTER_API_TOKEN: ${{ secrets.ANDROID_APPCENTER_API_TOKEN }}
      #      IOS_APPCENTER_API_TOKEN: ${{ secrets.IOS_APPCENTER_API_TOKEN }}
      #      SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
      #  hard-deploy-testing:
      #    needs: yarn-tester
      #    if: startsWith(github.ref, 'refs/tags/testing')
      #    uses: ./.github/workflows/dev_on_workflow_environment_deploy.yml
      #    environment: testing
      #    with:
      #      TYPE: "hard"
      #      ENV: "testing"
      #    secrets:
      #      SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
      #      ANDROID_APPCENTER_API_TOKEN: ${{ secrets.ANDROID_APPCENTER_API_TOKEN }}
      #      IOS_APPCENTER_API_TOKEN: ${{ secrets.IOS_APPCENTER_API_TOKEN }}
      #      SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
      #  hard-deploy-staging:
      #   needs: yarn-install
      #   if: startsWith(github.ref, 'refs/tags/debellesbouclettes')
      #   uses: ./.github/workflows/dev_on_workflow_environment_deploy.yml
      #   with:
      #      TYPE: "hard"
      #      ENV: "staging"
      #   secrets:
      #      SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
      #      ANDROID_APPCENTER_API_TOKEN: ${{ secrets.ANDROID_STAGING_APPCENTER_API_TOKEN }}
      #      IOS_APPCENTER_API_TOKEN: ${{ secrets.IOS_STAGING_APPCENTER_API_TOKEN }}
      #      SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
