name: Linter Type + Code

on:
  push:

jobs:
  yarn-install:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'yarn'
      - uses: actions/cache@v3
        id: yarn-modules-cache
        with:
          path: |
            node_modules
            ~/.cache/yarn
          key: v1-yarn-dependency-cache-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            v1-yarn-dependency-cache-${{ hashFiles('**/yarn.lock') }}
            v1-yarn-dependency-cache-
      - run: yarn install --immutable
        if: steps.yarn-modules-cache.outputs.cache-hit != 'true'
  test-lint:
    needs: yarn-install
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: |
            node_modules
            ~/.cache/yarn
          key: v1-yarn-dependency-cache-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            v1-yarn-dependency-cache-${{ hashFiles('**/yarn.lock') }}
      - name: Test lint
        run: yarn test:lint
  test-type:
    needs: yarn-install
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: |
            node_modules
            ~/.cache/yarn
          key: v1-yarn-dependency-cache-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            v1-yarn-dependency-cache-${{ hashFiles('**/yarn.lock') }}
      - name: Test type lint
        run: yarn test:types
