name: Initiate workflow

on:
  push:

jobs:
  job_id:
    permissions:
      contents: 'read'
      id-token: 'write'
    runs-on: [self-hosted, linux, x64]
    steps:
    - id: openid-auth
      name: "OpenID Connect Authentication"
      uses: 'google-github-actions/auth@v1'
      with:
        create_credentials_file: false
        token_format: 'access_token'
        workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
        service_account: ${{ secrets.ARTIFACT_REGISTRY_SERVICE_ACCOUNT }}
    - id: 'secrets'
      uses: 'google-github-actions/get-secretmanager-secrets@v1'
      with:
        secrets: |-
          json_secret:passculture-infra-prod/passcullte-app-native-test
    #  yarn-install:
    #    uses: ./.github/workflows/dev_on_workflow_install.yml
    #  yarn-linter:
    #    needs: yarn-install
    #    uses: ./.github/workflows/dev_on_workflow_linter_ts.yml
    #  yarn-tester:
    #    needs: yarn-linter
    #    uses: ./.github/workflows/dev_on_workflow_tester.yml
    #    secrets:
    #      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
    #      SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
    #  yarn-storybook:
    #    needs: yarn-linter
    #    uses: ./.github/workflows/dev_on_workflow_storybook.yml
    #  soft-deploy-testing:
    #    needs: yarn-tester
    #    if: github.ref == 'refs/heads/master'
    #    uses: ./.github/workflows/dev_on_workflow_environment_deploy.yml
    #    environment: testing
    #    with:
    #      TYPE: "soft"
    #      ENV: "testing"
    #    secrets:
    #      SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
    #      ANDROID_APPCENTER_API_TOKEN: ${{ secrets.ANDROID_APPCENTER_API_TOKEN }}
    #      IOS_APPCENTER_API_TOKEN: ${{ secrets.IOS_APPCENTER_API_TOKEN }}
    #      SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
    #  hard-deploy-testing:
    #    needs: yarn-tester
    #    if: startsWith(github.ref, 'refs/tags/testing')
    #    uses: ./.github/workflows/dev_on_workflow_environment_deploy.yml
    #    environment: testing
    #    with:
    #      TYPE: "hard"
    #      ENV: "testing"
    #    secrets:
    #      SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
    #      ANDROID_APPCENTER_API_TOKEN: ${{ secrets.ANDROID_APPCENTER_API_TOKEN }}
    #      IOS_APPCENTER_API_TOKEN: ${{ secrets.IOS_APPCENTER_API_TOKEN }}
    #      SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
    #      ANDROID_KEYSTORE: ${{ secrets.ANDROID_KEYSTORE }}
    #      ANDROID_KEYSTORE_STORE_PASSWORD: ${{ secrets.ANDROID_KEYSTORE_STORE_PASSWORD }}
    #      ANDROID_KEYSTORE_KEY_PASSWORD: ${{ secrets.ANDROID_KEYSTORE_KEY_PASSWORD}}
    #      ANDROID_GOOGLE_SERVICES_JSON: ${{ secrets.ANDROID_GOOGLE_SERVICES_JSON}}
    #  hard-deploy-staging:
    #    needs: yarn-tester
    #    if: startsWith(github.ref, 'refs/tags/patch')
    #    uses: ./.github/workflows/dev_on_workflow_environment_deploy.yml
    #    environment: staging
    #    with:
    #      TYPE: "hard"
    #      ENV: "staging"
    #    secrets:
    #      SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
    #      ANDROID_APPCENTER_API_TOKEN: ${{ secrets.ANDROID_APPCENTER_API_TOKEN }}
    #      IOS_APPCENTER_API_TOKEN: ${{ secrets.IOS_APPCENTER_API_TOKEN }}
    #      SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
    #      ANDROID_KEYSTORE: ${{ secrets.ANDROID_KEYSTORE }}
    #      ANDROID_KEYSTORE_STORE_PASSWORD: ${{ secrets.ANDROID_KEYSTORE_STORE_PASSWORD }}
    #      ANDROID_KEYSTORE_KEY_PASSWORD: ${{ secrets.ANDROID_KEYSTORE_KEY_PASSWORD}}
    #      ANDROID_GOOGLE_SERVICES_JSON: ${{ secrets.ANDROID_GOOGLE_SERVICES_JSON}}
