name: Push to ios and android

on:
  workflow_call:
    inputs:
      ENV:
        type: string
        required: true
    secrets:
      SENTRY_AUTH_TOKEN:
        required: true
jobs:
  Deploy_to_wanted_plateform:
    runs-on: [self-hosted, linux, X64]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Setup yarn
        run: npm install -g yarn
      - uses: actions/cache@v3
        with:
          path: |
            node_modules
            ~/.cache/yarn
          key: v1-yarn-dependency-cache-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            v1-yarn-dependency-cache-${{ hashFiles('**/yarn.lock') }}
      - uses: ruby/setup-ruby@v1
        with: 
          bundler-cache: true
      - name: 'Setup sentry credentials'
        run: |
          echo "[defaults]" >> ~/.sentryclirc
          echo "url=https://sentry.passculture.team/" >> ~/.sentryclirc
          echo "org=sentry" >> ~/.sentryclirc
          echo "project=application-native" >> ~/.sentryclirc
          echo "" >> ~/.sentryclirc
          echo "[auth]" >> ~/.sentryclirc
          echo "token=${{ secrets.SENTRY_AUTH_TOKEN }}" >> ~/.sentryclirc
      - name: Deploy app for ${{ inputs.ENV }}
        run: echo "${{ inputs.ENV }}"
        #        run : echo "bundle exec fastlane ios deploy codepush: --env ${{ inputs.ENV }}"
      - name: Deploy IOS App for ${{ inputs.ENV }}
        run: echo "${{ inputs.ENV }}"
        #        run: echo "bundle exec fastlane android deploy codepush: --env ${{ inputs.ENV }}"
