name: Deploy a new version

on:
  workflow_dispatch:
    inputs:
      tags:
        description: 'Test scenario tags'
        required: true
        type: string

jobs:
  yarn-install:
    runs-on: [self-hosted, linux, X64]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Setup yarn
        run: npm install -g yarn
      - uses: actions/cache@v3
        id: yarn-modules-cache
        with:
          path: |
            node_modules
            ~/.cache/yarn
          key: v1-yarn-dependency-cache-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            v1-yarn-dependency-cache-${{ hashFiles('**/yarn.lock') }}
      - run: yarn install --immutable
        #        if: steps.yarn-modules-cache.outputs.cache-hit != 'true'
  bundle-install:
    runs-on: [self-hosted, linux, X64]
    steps:
      - uses: actions/checkout@v3
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - name: Install Gem dependencies
        run: bundle install --path=vendor/bundle
  get_input_for_setting_tag_soft:
    needs:
      - yarn-install
      - bundle-install
    if: github.ref == 'refs/heads/master'
    uses: ./.github/workflows/prod_on_workflow_set_git_tag.yml
    with:
      TAG_PREFIX: v
  get_input_for_setting_tag_hard:
    needs: 
      - yarn-install
      - bundle-install
    if: github.ref == 'refs/heads/PC-20512-deploy-web-proxy-testing'
    uses: ./.github/workflows/prod_on_workflow_set_git_tag.yml
    with:
      TAG_PREFIX: toto
